version: "3.8"
services:
  app:
    build: .
    ports:
      - "8569:8080"
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/sestra'
      SPRING_DATASOURCE_USERNAME: 'sestra'
      SPRING_DATASOURCE_PASSWORD: 'sestra'
      PASSWORD_ADMIN: 'sestra'
  postgres:
    image: 'postgres:alpine'
    environment:
        POSTGRES_USER: 'sestra'
        POSTGRES_PASSWORD: 'sestra'
        POSTGRES_DB: 'sestra'
    ports:
      - "8570:5432"
